name: Build

on:
  push:
 
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-18.04, macos-10.15 ]

    steps:
      - name: Checkout the repository 
        uses: actions/checkout@v2
      - name: Build project
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic
